name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      RUST_BACKTRACE: 1

    steps:
      # --------------------
      # Checkout
      # --------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------
      # Node.js + Yarn setup
      # --------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install frontend dependencies (yarn)
        run: yarn install --frozen-lockfile

      - name: Build frontend
        run: yarn build
      # --------------------
      # Linux dependencies for Tauri
      # --------------------
      - name: Install Tauri system dependencies (Linux)
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkitgtk-6.0-dev \
            libgtk-3-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-6.0-dev
            libayatana-appindicator3-dev      

      # --------------------
      # Rust setup
      # --------------------
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          override: true

      # --------------------
      # Rust quality checks
      # --------------------
      - name: rustfmt check
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check

      # - name: cargo clippy
      #   run: cargo clippy \
      #     --manifest-path src-tauri/Cargo.toml \
      #     --all-targets \
      #     --all-features \
      #     -- -D warnings

      # - name: Run Rust tests
      #   run: cargo test \
      #     --manifest-path src-tauri/Cargo.toml \
      #     --all \
      #     --verbose

      # --------------------
      # Build Tauri Rust backend
      # --------------------
      - name: Build tauri Rust backend
        run: cargo build --manifest-path src-tauri/Cargo.toml --release
